In [243]:
import pandas as pd
import  seaborn as sns
import numpy as np
import matplotlib as plt

In [244]:
df = pd.read_csv('Business_Dataset.csv')

In [245]:
df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"

In [246]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
dtypes: int64(1), object(10)
memory usage: 7.8+ MB

In [247]:
df.shape

(93487, 11)

In [248]:
df.describe()

           num_code
count  93487.000000
mean     780.056147
std      147.616038
min      401.000000
25%      706.000000
50%      820.000000
75%      874.000000
max      996.000000

In [249]:
df.isnull().sum()

date          0
airline       0
ch_code       0
num_code      0
dep_time      0
from          0
time_taken    0
stop          0
arr_time      0
to            0
price         0
dtype: int64

In [250]:
df.duplicated().sum()

np.int64(0)

In [251]:
df.head(2)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"

### Handling date column

In [252]:
df['Date'] = df['date'].str.split('-').str[0]
df['Month'] = df['date'].str.split('-').str[1]
df['Year'] = df['date'].str.split('-').str[2]

In [253]:
# .str enables to apply string operations in whole column

In [254]:
df.head(2)

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,02,2022
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,02,2022

In [255]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  object
 12  Month       93487 non-null  object
 13  Year        93487 non-null  object
dtypes: int64(1), object(13)
memory usage: 10.0+ MB

In [256]:
# but the type is still object, convert it to int

In [257]:
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

In [258]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  int64
 12  Month       93487 non-null  int64
 13  Year        93487 non-null  int64
dtypes: int64(4), object(10)
memory usage: 10.0+ MB

In [259]:
df.drop('date', axis = 1, inplace = True)

In [260]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022

### Handling arr_time column

In [261]:
df['Arr_hr'] = df['arr_time'].str.split(':').str[0]
df['Arr_min'] = df['arr_time'].str.split(':').str[1]

In [262]:
df['Arr_hr'] = df['Arr_hr'].astype(int)
df['Arr_min'] = df['Arr_min'].astype(int)

In [263]:
df.drop('arr_time', axis = 1, inplace = True)

In [264]:
df.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,to,price,Date,Month,Year,Arr_hr,Arr_min
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15

### Handling dep_time column

In [265]:
df['Dep_hr'] = df['dep_time'].str.split(':').str[0]
df['Dep_min'] = df['dep_time'].str.split(':').str[1]

In [266]:
df['Dep_hr'] = df['Dep_hr'].astype(int)
df['Dep_min'] = df['Dep_min'].astype(int)

In [267]:
df.drop('dep_time',inplace = True, axis = 1)

In [268]:
df.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arr_hr,Arr_min,Dep_hr,Dep_min
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0

### Handling time_taken column

In [269]:
df[['Time_Taken_hr', 'Time_Taken_min']] = df['time_taken'].str.split(' ',expand = True)

In [270]:
# expand = True, helps to convert list value to seperate column, if not used then list will be returned and 
# df[['Time_Taken_hr', 'Time_Taken_min']] youu have to do this individually f want to do together use expand which will convert 
# list to column

In [271]:
df['Time_Taken_hr'] = df['Time_Taken_hr'].str.replace('h','').astype(int)

In [272]:
df['Time_Taken_min'] = df['Time_Taken_min'].str.replace('m','').astype(int)

In [273]:
df.drop('time_taken', axis = 1, inplace = True)

In [274]:
df.head(2)

,airline,ch_code,num_code,from,stop,to,price,Date,Month,Year,Arr_hr,Arr_min,Dep_hr,Dep_min,Time_Taken_hr,Time_Taken_min
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0,2,0
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0,2,15

In [275]:
df['stop'].unique()

array(['non-stop ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '2+-stop',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t'],
      dtype=object)

In [276]:
df['Stop'] = df['stop'].str.replace('\n', ' ')

In [277]:
df['Stop'] = df['Stop'].str.replace('\t', '')

In [278]:
df['Stop'].unique()

array(['non-stop ', '1-stop  ', '1-stop Via IDR ', '1-stop Via IXU ',
       '1-stop Via Chennai ', '1-stop Via Lucknow ', '1-stop Via STV ',
       '1-stop Via Hyderabad ', '1-stop Via GAY ', '2+-stop',
       '1-stop Via Guwahati ', '1-stop Via GAU ', '1-stop Via VTZ ',
       '1-stop Via NDC ', '1-stop Via IXE ', '1-stop Via Raipur ',
       '1-stop Via PAT ', '1-stop Via RPR ', '1-stop Via Patna ',
       '1-stop Via Kolkata ', '1-stop Via HYD ', '1-stop Via Delhi ',
       '1-stop Via Bhubaneswar ', '1-stop Via BBI ', '1-stop Via Surat '],
      dtype=object)

In [279]:
df['Stop_no'] = df['Stop'].str.split('Via').str[0]

In [280]:
df['Stop_place'] = df['Stop'].str.split('Via').str[1]

In [281]:
df['Stop_no'].unique()

array(['non-stop ', '1-stop  ', '1-stop ', '2+-stop'], dtype=object)

In [282]:
df['Stop_place'].unique()

array([nan, ' IDR ', ' IXU ', ' Chennai ', ' Lucknow ', ' STV ',
       ' Hyderabad ', ' GAY ', ' Guwahati ', ' GAU ', ' VTZ ', ' NDC ',
       ' IXE ', ' Raipur ', ' PAT ', ' RPR ', ' Patna ', ' Kolkata ',
       ' HYD ', ' Delhi ', ' Bhubaneswar ', ' BBI ', ' Surat '],
      dtype=object)

In [283]:
df.drop(columns = ['Stop','stop'],axis = 1, inplace = True)

In [284]:
df.head(2)

,airline,ch_code,num_code,from,to,price,Date,Month,Year,Arr_hr,Arr_min,Dep_hr,Dep_min,Time_Taken_hr,Time_Taken_min,Stop_no,Stop_place
0,Air India,AI,868,Delhi,Mumbai,"25,612",11,2,2022,20,0,18,0,2,0,non-stop,NaN
1,Air India,AI,624,Delhi,Mumbai,"25,612",11,2,2022,21,15,19,0,2,15,non-stop,NaN

In [291]:
# If I individually want to convert only nan by 0
# df['Stop_place'] = df['Stop_place'].fillna(0)

In [286]:
df['Stop_no'] = df['Stop_no'].map({'non-stop ':0, '1-stop  ':1,'1-stop ':1, '2+-stop':2})

In [287]:
df['Stop_place'] = df['Stop_place'].map({
    np.nan : 0,
    ' IDR ': 1,
    ' IXU ': 2,
    ' Chennai ': 3,
    ' Lucknow ': 4,
    ' STV ': 5,
    ' Hyderabad ': 6,
    ' GAY ': 7,
    ' Guwahati ': 8,
    ' GAU ': 9,
    ' VTZ ': 10,
    ' NDC ': 11,
    ' IXE ': 12,
    ' Raipur ': 13,
    ' PAT ': 14,
    ' RPR ': 15,
    ' Patna ': 16,
    ' Kolkata ': 17,
    ' HYD ': 18,
    ' Delhi ': 19,
    ' Bhubaneswar ': 20,
    ' BBI ': 21,
    ' Surat ': 22
})

In [288]:
df['Stop_no'].unique()

array([0, 1, 2])

In [289]:
df['Stop_place'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [290]:
df.isnull().sum()

airline           0
ch_code           0
num_code          0
from              0
to                0
price             0
Date              0
Month             0
Year              0
Arr_hr            0
Arr_min           0
Dep_hr            0
Dep_min           0
Time_Taken_hr     0
Time_Taken_min    0
Stop_no           0
Stop_place        0
dtype: int64

In [292]:
df.head(2)

,airline,ch_code,num_code,from,to,price,Date,Month,Year,Arr_hr,Arr_min,Dep_hr,Dep_min,Time_Taken_hr,Time_Taken_min,Stop_no,Stop_place
0,Air India,AI,868,Delhi,Mumbai,"25,612",11,2,2022,20,0,18,0,2,0,0,0
1,Air India,AI,624,Delhi,Mumbai,"25,612",11,2,2022,21,15,19,0,2,15,0,0

In [300]:
from sklearn.preprocessing import OneHotEncoder

In [301]:
encoder = OneHotEncoder()

In [302]:
 encoder.fit_transform(df[['airline','ch_code', 'from', 'to']]).toarray()

array([[1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]], shape=(93487, 16))

In [306]:
encoded = pd.DataFrame( encoder.fit_transform(df[['airline','ch_code', 'from', 'to']]).toarray(),columns = encoder.get_feature_names_out())

In [307]:
df = df.drop(columns=['airline','ch_code','from','to']).join(encoded)

In [309]:
df.head(3)

,num_code,price,Date,Month,Year,Arr_hr,Arr_min,Dep_hr,Dep_min,Time_Taken_hr,...,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,868,"25,612",11,2,2022,20,0,18,0,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,624,"25,612",11,2,2022,21,15,19,0,2,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,531,"42,220",11,2,2022,20,45,20,0,24,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0