In [560]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [561]:
df = pd.read_csv("Algerian_forest_fires_dataset.csv")

In [562]:
df_cpy = df.copy()

In [563]:
df.head(2)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire

In [564]:
df_cpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    object
 3   Temperature  245 non-null    object
 4    RH          245 non-null    object
 5    Ws          245 non-null    object
 6   Rain         245 non-null    object
 7   FFMC         245 non-null    object
 8   DMC          245 non-null    object
 9   DC           245 non-null    object
 10  ISI          245 non-null    object
 11  BUI          245 non-null    object
 12  FWI          245 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 27.1+ KB

In [565]:
df_cpy.describe()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
count,246,245,245,245,245,245,245,245,245,245,245,245,245,244
unique,33,5,2,20,63,19,40,174,167,199,107,175,127,9
top,1,7,2012,35,55,14,0,88.9,7.9,8,1.1,3,0.4,fire
freq,8,62,244,29,10,43,133,8,5,5,8,5,12,131

In [566]:
df_cpy.isnull().sum()

day            1
month          2
year           2
Temperature    2
 RH            2
 Ws            2
Rain           2
FFMC           2
DMC            2
DC             2
ISI            2
BUI            2
FWI            2
Classes        3
dtype: int64

In [567]:
df_cpy[df_cpy.isnull().any(axis = 1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,14,7,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [568]:
df_cpy.reset_index(drop=True, inplace=True)
df_cpy.drop(index=[122,123], inplace=True)
df_cpy.reset_index(drop=True, inplace=True)

In [569]:
df_cpy[df_cpy.isnull().any(axis = 1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
166,14,7,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [570]:
df_cpy.columns = df_cpy.columns.str.strip()

In [571]:
# df_cpy.columns = df_cpy.columns.str.replace(" ", "")

In [572]:
df_cpy["Classes"].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
Classes            1
not fire           1
not fire           1
Name: count, dtype: int64

In [573]:
df_cpy['Classes'].fillna('fire',inplace = True)

C:\Users\Lalit Chandra\AppData\Local\Temp\ipykernel_15892\2060382172.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cpy['Classes'].fillna('fire',inplace = True)

In [574]:
df_cpy["Classes"].isnull().sum()

np.int64(0)

In [575]:
df_cpy.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes'],
      dtype='object')

In [576]:
df_cpy["Classes"].value_counts()

Classes
fire             131
not fire         101
fire               5
fire               2
not fire           2
not fire           1
Classes            1
not fire           1
not fire           1
Name: count, dtype: int64

In [577]:
df_cpy[df_cpy['Classes'] == 'Classes']

Empty DataFrame
Columns: [day, month, year, Temperature, RH, Ws, Rain, FFMC, DMC, DC, ISI, BUI, FWI, Classes]
Index: []

In [578]:
# changes the value inside the class from classes to fire where classes exist inside the columns classes
# df_cpy["Classes"] = df_cpy["Classes"].str.replace("Classes", "fire")

In [579]:
df_cpy.drop(index = 122, inplace = True)

In [580]:
df_cpy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 244
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    object
 1   month        244 non-null    object
 2   year         244 non-null    object
 3   Temperature  244 non-null    object
 4   RH           244 non-null    object
 5   Ws           244 non-null    object
 6   Rain         244 non-null    object
 7   FFMC         244 non-null    object
 8   DMC          244 non-null    object
 9   DC           244 non-null    object
 10  ISI          244 non-null    object
 11  BUI          244 non-null    object
 12  FWI          244 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 28.6+ KB

In [581]:
df_cpy.head(2)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire

In [582]:
df_cpy.drop(columns = ['day', 'month', "year"],inplace = True)

In [583]:
df_cpy.head(2)

  Temperature  RH  Ws Rain  FFMC  DMC   DC  ISI  BUI  FWI      Classes
0          29  57  18    0  65.7  3.4  7.6  1.3  3.4  0.5  not fire
1          29  61  13  1.3  64.4  4.1  7.6    1  3.9  0.4  not fire

In [584]:
df_cpy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 244
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  244 non-null    object
 1   RH           244 non-null    object
 2   Ws           244 non-null    object
 3   Rain         244 non-null    object
 4   FFMC         244 non-null    object
 5   DMC          244 non-null    object
 6   DC           244 non-null    object
 7   ISI          244 non-null    object
 8   BUI          244 non-null    object
 9   FWI          244 non-null    object
 10  Classes      244 non-null    object
dtypes: object(11)
memory usage: 22.9+ KB

In [585]:
df_cpy['Classes'].value_counts()
# Many white spaces are present throughout the dataset

Classes
fire             131
not fire         101
fire               5
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [586]:
for i in df_cpy.columns:
    df_cpy[i] = df_cpy[i].str.strip()

In [587]:
df_cpy['Classes'].value_counts()

Classes
fire        138
not fire    106
Name: count, dtype: int64

In [588]:
len(df_cpy.columns)

11

In [589]:
# df_cpy.iloc[:,:-1] = df_cpy.iloc[:,:-1].astype(float)
# from this we came to know that there are still strings in which white spaces are present

In [590]:
df_cpy.columns

Index(['Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI',
       'FWI', 'Classes'],
      dtype='object')

In [591]:
df_cpy.head(3)

  Temperature  RH  Ws  Rain  FFMC  DMC   DC  ISI  BUI  FWI   Classes
0          29  57  18     0  65.7  3.4  7.6  1.3  3.4  0.5  not fire
1          29  61  13   1.3  64.4  4.1  7.6    1  3.9  0.4  not fire
2          26  82  22  13.1  47.1  2.5  7.1  0.3  2.7  0.1  not fire

In [592]:
df_cpy[['Temperature', 'RH', 'Ws']] = df_cpy[['Temperature', 'RH', 'Ws']].astype(int)

In [593]:
df_cpy['Rain'].unique()

array(['0', '1.3', '13.1', '2.5', '0.2', '1.2', '0.5', '3.1', '0.7',
       '0.6', '0.3', '0.1', '0.4', '1', '1.4', '0.8', '16.8', '7.2',
       '10.1', '3.8', '0.9', '1.8', '4.6', '8.3', '5.8', '4', '2', '4.7',
       '8.7', '4.5', '1.1', '1.7', '2.2', '6', '1.9', '2.9', '4.1', '6.5',
       '4.4'], dtype=object)

In [594]:
df_cpy['FFMC'].unique()

array(['65.7', '64.4', '47.1', '28.6', '64.8', '82.6', '88.2', '86.6',
       '52.9', '73.2', '84.5', '84', '50', '59', '49.4', '36.1', '37.3',
       '56.9', '79.9', '59.8', '81', '79.1', '81.4', '85.9', '86.7',
       '86.8', '89', '89.1', '88.7', '59.9', '55.7', '63.1', '80.1', '87',
       '80', '85.6', '66.6', '81.1', '75.1', '81.8', '73.9', '60.7',
       '72.6', '82.8', '85.4', '88.1', '73.4', '68.2', '70', '84.3',
       '89.2', '90.3', '86.5', '87.2', '78.8', '78', '76.6', '85', '86.4',
       '77.1', '87.4', '88.9', '81.3', '82.4', '80.2', '89.3', '89.4',
       '88.3', '88.6', '89.5', '85.8', '84.9', '90.1', '72.7', '52.5',
       '46', '30.5', '42.6', '68.4', '80.8', '75.8', '69.6', '62', '56.1',
       '58.5', '71', '40.9', '47.4', '44.9', '78.1', '87.7', '83.8',
       '87.8', '77.8', '73.7', '68.3', '48.6', '82', '85.7', '77.5', '45',
       '57.1', '48.7', '79.4', '83.7', '71.4', '90.6', '72.3', '53.4',
       '66.8', '62.2', '65.5', '64.6', '60.2', '86.2', '78.3', '74.2',
       '85.3', '86', '92.5', '79.7', '63.7', '87.6', '84.7', '88', '90.5',
       '82.3', '74.8', '85.2', '84.6', '86.1', '89.9', '93.9', '91.5',
       '87.3', '72.8', '73.8', '87.5', '93.3', '93.7', '93.8', '70.5',
       '69.7', '91.7', '94.2', '93', '91.9', '83.9', '92', '96', '94.3',
       '82.7', '91.2', '92.1', '92.2', '91', '79.2', '37.9', '75.4',
       '82.2', '73.5', '66.1', '64.5', '83.3', '82.5', '83.1', '59.5',
       '84.2', '79.5', '61.3', '41.1', '45.9', '67.3'], dtype=object)

In [595]:
df_cpy['DMC'].unique()

array(['3.4', '4.1', '2.5', '1.3', '3', '5.8', '9.9', '12.1', '7.9',
       '9.5', '12.5', '13.8', '6.7', '4.6', '1.7', '1.1', '1.9', '4.5',
       '6.3', '7', '8.2', '11.2', '14.2', '17.8', '21.6', '25.5', '18.4',
       '22.9', '2.4', '2.6', '7.6', '10.9', '9.7', '7.7', '6', '8.1',
       '7.8', '5.2', '9.4', '12', '12.3', '18.5', '16.4', '10.5', '9.6',
       '17.1', '22.2', '24.4', '26.7', '28.5', '31.9', '4.8', '5.7',
       '11.1', '13', '15.5', '11.3', '14.8', '18.6', '21.7', '15.6', '19',
       '11.7', '16', '20', '23.2', '25.9', '29.6', '33.5', '37.6', '40.5',
       '43.9', '45.6', '47', '50.2', '54.2', '25.2', '8.7', '0.7', '1.2',
       '3.6', '3.2', '2.1', '2.2', '0.9', '6.4', '9.8', '13.5', '16.5',
       '10.6', '5.5', '8.3', '7.1', '2.9', '2.7', '8.4', '8.5', '13.3',
       '18.2', '21.3', '11.4', '7.2', '4.2', '3.9', '4.4', '3.8', '10',
       '12.8', '20.9', '27.2', '17.9', '13.6', '18.7', '8', '12.6',
       '12.9', '18', '19.4', '21.1', '23.9', '27.8', '32.7', '39.6',
       '44.2', '46.6', '10.8', '11.8', '15.7', '19.5', '23.8', '28.3',
       '23', '23.6', '11', '15.8', '22.5', '16.9', '22.3', '22.6', '30.3',
       '35.9', '34.4', '36.9', '41.1', '46.1', '51.3', '56.3', '61.3',
       '65.9', '37', '20.7', '24.8', '4', '3.3', '6.6', '4.7', '6.5',
       '11.5', '21.2', '25.8', '24.9', '26.1', '29.4', '11.9', '3.5',
       '4.3'], dtype=object)

In [596]:
df_cpy[[ 'Rain', 'FFMC', 'DMC']] = df_cpy[[ 'Rain', 'FFMC', 'DMC']].astype(float)

In [597]:
df_cpy['DC'].unique()

array(['7.6', '7.1', '6.9', '14.2', '22.2', '30.5', '38.3', '38.8',
       '46.3', '54.3', '61.4', '17', '7.8', '7.4', '8', '16', '27.1',
       '31.6', '39.5', '47.7', '55.8', '63.8', '71.8', '80.3', '88.5',
       '84.4', '92.8', '8.6', '8.3', '9.2', '18.5', '27.9', '37', '40.4',
       '49.8', '9.3', '18.7', '27.7', '37.2', '22.9', '25.5', '34.1',
       '43.1', '52.8', '62.1', '71.5', '79.9', '71.3', '79.7', '88.7',
       '98.6', '108.5', '117.8', '127', '136', '145.7', '10.2', '10',
       '19.8', '29.7', '39.1', '48.6', '47', '57', '67', '77', '75.1',
       '85.1', '94.7', '92.5', '90.4', '100.7', '110.9', '120.9', '130.6',
       '141.1', '151.3', '161.5', '171.3', '181.3', '190.6', '200.2',
       '210.4', '220.4', '180.4', '8.7', '7.5', '7', '15.7', '24', '32.2',
       '30.1', '8.4', '8.9', '16.6', '7.3', '24.3', '33.1', '41.3',
       '49.3', '57.9', '41.4', '30.4', '15.2', '7.7', '16.3', '24.9',
       '8.8', '8.2', '15.4', '17.6', '26.3', '28.9', '14.7', '22.5',
       '37.8', '18.4', '25.6', '34.5', '43.3', '52.4', '36.7', '8.5',
       '17.8', '27.3', '36.8', '46.4', '45.1', '35.4', '9.7', '9.9',
       '9.5', '19.4', '10.4', '14.6 9', '24.1', '42.3', '51.6', '61.1',
       '71', '80.6', '90.1', '99', '56.6', '15.9', '19.7', '28.3', '37.6',
       '47.2', '57.1', '67.2', '10.5', '21.4', '32.1', '42.7', '52.5',
       '9.1', '9.8', '20.2', '30.9', '41.5', '55.5', '54.2', '65.1',
       '76.4', '86.8', '96.8', '107', '117.1', '127.5', '137.7', '147.7',
       '157.5', '167.2', '177.3', '166', '149.2', '159.1', '168.2',
       '26.6', '17.7', '26.1', '25.2', '33.4', '50.2', '59.2', '63.3',
       '77.8', '86', '88', '97.3', '106.3', '115.6', '28.1', '36.1',
       '44.5', '7.9', '16.5'], dtype=object)

In [598]:
df_cpy['DC'] = df_cpy['DC'].str.replace(" ", "")

In [599]:
df_cpy['DC'] = df_cpy['DC'].astype(float)

In [600]:
# df_cpy[['ISI', 'BUI','FWI']] = df_cpy[['ISI', 'BUI','FWI']].astype(float)
# from this i came to knnow that there is a non numeric value exist in this column

In [601]:
df_cpy[df_cpy['FWI'] == 'fire']

     Temperature  RH  Ws  Rain  FFMC   DMC     DC   ISI   BUI   FWI Classes
166           37  37  18   0.2  88.9  12.9  14.69  12.5  10.4  fire    fire

In [602]:
# Random
df_cpy['FWI'] = df_cpy['FWI'].str.replace('fire', "100")

In [603]:
df_cpy[['ISI', 'BUI','FWI']] = df_cpy[['ISI', 'BUI','FWI']].astype(float)

In [604]:
df_cpy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 244
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  244 non-null    int64
 1   RH           244 non-null    int64
 2   Ws           244 non-null    int64
 3   Rain         244 non-null    float64
 4   FFMC         244 non-null    float64
 5   DMC          244 non-null    float64
 6   DC           244 non-null    float64
 7   ISI          244 non-null    float64
 8   BUI          244 non-null    float64
 9   FWI          244 non-null    float64
 10  Classes      244 non-null    object
dtypes: float64(7), int64(3), object(1)
memory usage: 22.9+ KB

In [605]:
df_cpy['Classes'].unique()

array(['not fire', 'fire'], dtype=object)

In [606]:
df_cpy['Classes'] = df_cpy['Classes'].map({'fire' : 1, 'not fire':0})

In [607]:
df_cpy.describe()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
count,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000,244.000000
mean,32.172131,61.938525,15.504098,0.760656,77.887705,14.673361,49.288484,4.774180,16.664754,7.416393,0.565574
std,3.633843,14.884200,2.810178,1.999406,14.337571,12.368039,47.619393,4.175318,14.204824,9.515985,0.496700
min,22.000000,21.000000,6.000000,0.000000,28.600000,0.700000,6.900000,0.000000,1.100000,0.000000,0.000000
25%,30.000000,52.000000,14.000000,0.000000,72.075000,5.800000,13.275000,1.400000,6.000000,0.700000,0.000000
50%,32.000000,63.000000,15.000000,0.000000,83.500000,11.300000,33.100000,3.500000,12.250000,4.450000,1.000000
75%,35.000000,73.250000,17.000000,0.500000,88.300000,20.750000,68.150000,7.300000,22.525000,11.675000,1.000000
max,42.000000,90.000000,29.000000,16.800000,96.000000,65.900000,220.400000,19.000000,68.000000,100.000000,1.000000