In [243]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [244]:
df = pd.read_csv("Travel.csv")

In [245]:
df_cpy = df.copy()

In [246]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [248]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [249]:
df.shape

(4888, 20)

In [250]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [251]:
df.duplicated().sum()

np.int64(0)

In [252]:
df.head(2)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0

# Data Cleaning
### Going column by column and  
1. checking values (for completely different data or spelling mistakes or outliers) 
2. checking datatypes
3. filling nulls

## ProdTaken

In [253]:
df['ProdTaken'].value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

## Age

In [254]:
df['Age'].value_counts(sort = True)

Age
35.0    237
36.0    231
34.0    211
31.0    203
30.0    199
32.0    197
33.0    189
37.0    185
29.0    178
38.0    176
41.0    155
39.0    150
28.0    147
40.0    146
42.0    142
27.0    138
43.0    130
46.0    121
45.0    116
26.0    106
44.0    105
51.0     90
47.0     88
50.0     86
25.0     74
52.0     68
53.0     66
49.0     65
48.0     65
55.0     64
54.0     61
56.0     58
24.0     56
23.0     46
22.0     46
59.0     44
21.0     41
20.0     38
19.0     32
58.0     31
57.0     29
60.0     29
18.0     14
61.0      9
Name: count, dtype: int64

In [255]:
df['Age'].mean()

np.float64(37.62226512226512)

In [256]:
df['Age'].fillna(38, axis = 0, inplace = True)

C:\Users\Lalit Chandra\AppData\Local\Temp\ipykernel_1180\872647647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(38, axis = 0, inplace = True)

In [257]:
df['Age'].isnull().sum()

np.int64(0)

In [258]:
df['Age'].value_counts(sort = True)

Age
38.0    402
35.0    237
36.0    231
34.0    211
31.0    203
30.0    199
32.0    197
33.0    189
37.0    185
29.0    178
41.0    155
39.0    150
28.0    147
40.0    146
42.0    142
27.0    138
43.0    130
46.0    121
45.0    116
26.0    106
44.0    105
51.0     90
47.0     88
50.0     86
25.0     74
52.0     68
53.0     66
49.0     65
48.0     65
55.0     64
54.0     61
56.0     58
24.0     56
23.0     46
22.0     46
59.0     44
21.0     41
20.0     38
19.0     32
58.0     31
57.0     29
60.0     29
18.0     14
61.0      9
Name: count, dtype: int64

## TypeofContact

In [259]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [260]:
df['TypeofContact'].isnull().sum()

np.int64(25)

In [261]:
df['TypeofContact'] = df['TypeofContact'].map({'Self Enquiry' : 1, 'Company Invited' : 2})

In [262]:
df['TypeofContact']

0       1.0
1       2.0
2       1.0
3       2.0
4       1.0
       ...
4883    1.0
4884    2.0
4885    1.0
4886    1.0
4887    1.0
Name: TypeofContact, Length: 4888, dtype: float64

In [263]:
df['TypeofContact'].mode()

0    1.0
Name: TypeofContact, dtype: float64

In [264]:
df['TypeofContact'] = df['TypeofContact'].fillna(df['TypeofContact'].mode()[0])

In [265]:
df['TypeofContact'].isnull().sum()

np.int64(0)

## CityTier

In [266]:
df['CityTier'].value_counts()

CityTier
1    3190
3    1500
2     198
Name: count, dtype: int64

In [267]:
df['CityTier'].isnull().sum()

np.int64(0)

In [268]:
df['DurationOfPitch'].value_counts()

DurationOfPitch
9.0      483
7.0      342
8.0      333
6.0      307
16.0     274
15.0     269
14.0     253
10.0     244
13.0     223
11.0     205
12.0     195
17.0     172
30.0      95
22.0      89
31.0      83
23.0      79
18.0      75
32.0      74
29.0      74
25.0      73
21.0      73
27.0      72
26.0      72
24.0      70
35.0      66
20.0      65
28.0      61
33.0      57
19.0      57
34.0      50
36.0      44
5.0        6
126.0      1
127.0      1
Name: count, dtype: int64

In [269]:
df['DurationOfPitch'].isnull().sum()

np.int64(251)

In [270]:
df['DurationOfPitch'] = df['DurationOfPitch'].fillna(df['DurationOfPitch'].mean())

In [271]:
df['DurationOfPitch'].isnull().sum()

np.int64(0)

## Occupation

In [272]:
df['Occupation'].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [273]:
df['Occupation'].isnull().sum()

np.int64(0)

In [274]:
df['Occupation'] = df['Occupation'].map({'Salaried' : 1, 'Small Business' : 2, 'Large Business' : 3, 'Free Lancer' : 4})

## Gender

In [275]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [276]:
df['Gender'].replace('Fe Male', 'Female',inplace = True)

C:\Users\Lalit Chandra\AppData\Local\Temp\ipykernel_1180\2737011099.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace('Fe Male', 'Female',inplace = True)

In [277]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [278]:
df['Gender'].isnull().sum()

np.int64(0)

In [279]:
df['Gender'] = df['Gender'].map({'Male' : 1, 'Female' : 2})

## NumberOfPersonVisiting

In [280]:
df['NumberOfPersonVisiting'].value_counts()

NumberOfPersonVisiting
3    2402
2    1418
4    1026
1      39
5       3
Name: count, dtype: int64

In [281]:
df['NumberOfPersonVisiting'].isnull().sum()

np.int64(0)

In [282]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

## NumberOfFollowups

In [283]:
df['NumberOfFollowups'].value_counts()

NumberOfFollowups
4.0    2068
3.0    1466
5.0     768
2.0     229
1.0     176
6.0     136
Name: count, dtype: int64

In [284]:
df['NumberOfFollowups'].isnull().sum()

np.int64(45)

In [285]:
df['NumberOfFollowups'] = df['NumberOfFollowups'].fillna(df['NumberOfFollowups'].mean())

In [286]:
df['NumberOfFollowups'].isnull().sum()

np.int64(0)

## ProductPitched

In [287]:
df['ProductPitched'].value_counts()

ProductPitched
Basic           1842
Deluxe          1732
Standard         742
Super Deluxe     342
King             230
Name: count, dtype: int64

In [288]:
df['ProductPitched'].isnull().sum()

np.int64(0)

In [289]:
df['ProductPitched'] = df['ProductPitched'].map({'Basic' : 1, 'Deluxe' : 2, 'Standard' : 3, 'Super Deluxe' : 4, 'King' : 5})

In [290]:
df['ProductPitched'].value_counts()

ProductPitched
1    1842
2    1732
3     742
4     342
5     230
Name: count, dtype: int64

## PreferredPropertyStar

In [291]:
df['PreferredPropertyStar'].value_counts()

PreferredPropertyStar
3.0    2993
5.0     956
4.0     913
Name: count, dtype: int64

In [292]:
df['PreferredPropertyStar'].isnull().sum()

np.int64(26)

In [293]:
df['PreferredPropertyStar'] = df['PreferredPropertyStar'].fillna(df['PreferredPropertyStar'].mode()[0])

In [294]:
df['PreferredPropertyStar'].isnull().sum()

np.int64(0)

## MaritalStatus

In [295]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [296]:
df['MaritalStatus'].isnull().sum()

np.int64(0)

In [297]:
df['MaritalStatus'] = df['MaritalStatus'].replace('Single', 'Unmarried')

In [298]:
df['MaritalStatus'] = df['MaritalStatus'].map({'Married' : 1, 'Divorced' : 2, 'Unmarried' : 3})

## NumberOfTrips

In [299]:
df['NumberOfTrips'].value_counts()

NumberOfTrips
2.0     1464
3.0     1079
1.0      620
4.0      478
5.0      458
6.0      322
7.0      218
8.0      105
19.0       1
21.0       1
20.0       1
22.0       1
Name: count, dtype: int64

In [300]:
df['NumberOfTrips'].isnull().sum()

np.int64(140)

In [301]:
df['NumberOfTrips'] = df['NumberOfTrips'].fillna(df['NumberOfTrips'].mode()[0])

In [302]:
df['NumberOfTrips'].isnull().sum()

np.int64(0)

## Passport

In [303]:
df['Passport'].value_counts()

Passport
0    3466
1    1422
Name: count, dtype: int64

In [304]:
df['Passport'].isnull().sum()

np.int64(0)

## PitchSatisfactionScore

In [305]:
df['PitchSatisfactionScore'].value_counts()

PitchSatisfactionScore
3    1478
5     970
1     942
4     912
2     586
Name: count, dtype: int64

In [306]:
df['PitchSatisfactionScore'].isnull().sum()

np.int64(0)

## OwnCar

In [307]:
df['OwnCar'].value_counts()

OwnCar
1    3032
0    1856
Name: count, dtype: int64

In [308]:
df['OwnCar'].isnull().sum()

np.int64(0)

## NumberOfChildrenVisiting

In [309]:
df['NumberOfChildrenVisiting'].value_counts()

NumberOfChildrenVisiting
1.0    2080
2.0    1335
0.0    1082
3.0     325
Name: count, dtype: int64

In [310]:
df['NumberOfChildrenVisiting'].isnull().sum()

np.int64(66)

In [311]:
df['NumberOfChildrenVisiting'] = df['NumberOfChildrenVisiting'].fillna(df['NumberOfChildrenVisiting'].mode()[0])

In [312]:
df['NumberOfChildrenVisiting'].isnull().sum()

np.int64(0)

## Designation

In [313]:
df['Designation'].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [314]:
df['Designation'].isnull().sum()

np.int64(0)

In [315]:
df['Designation'] = df['Designation'].map({'Executive' : 1, 'Manager' : 2, 'Senior Manager' : 3, 'AVP' : 4, 'VP' : 5})

## MonthlyIncome

In [316]:
df['MonthlyIncome'].isnull().sum()

np.int64(233)

In [317]:
df['MonthlyIncome'].unique()

array([20993., 20130., 17090., ..., 22097., 22995., 21471.], shape=(2476,))

In [318]:
df['MonthlyIncome'] = df['MonthlyIncome'].fillna(round(df['MonthlyIncome'].mean(),ndigits = 2))

In [319]:
df['MonthlyIncome'].isnull().sum()

np.int64(0)

In [320]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,1.0,3,6.0,1,2,3,3.0,2,3.0,3,1.0,1,2,1,0.0,2,20993.0
1,200001,0,49.0,2.0,1,14.0,1,1,3,4.0,2,4.0,2,2.0,0,3,1,2.0,2,20130.0
2,200002,1,37.0,1.0,1,8.0,4,1,3,4.0,1,3.0,3,7.0,1,3,0,0.0,1,17090.0
3,200003,0,33.0,2.0,1,9.0,1,2,2,3.0,1,3.0,2,2.0,1,5,1,1.0,1,17909.0
4,200004,0,38.0,1.0,1,8.0,2,1,2,3.0,1,4.0,2,1.0,0,5,1,0.0,1,18468.0

In [322]:
df.drop(columns = ['CustomerID'], axis = 0, inplace = True)

In [323]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,1.0,3,6.0,1,2,3,3.0,2,3.0,3,1.0,1,2,1,0.0,2,20993.0
1,0,49.0,2.0,1,14.0,1,1,3,4.0,2,4.0,2,2.0,0,3,1,2.0,2,20130.0
2,1,37.0,1.0,1,8.0,4,1,3,4.0,1,3.0,3,7.0,1,3,0,0.0,1,17090.0
3,0,33.0,2.0,1,9.0,1,2,2,3.0,1,3.0,2,2.0,1,5,1,1.0,1,17909.0
4,0,38.0,1.0,1,8.0,2,1,2,3.0,1,4.0,2,1.0,0,5,1,0.0,1,18468.0